## OpenAI API
- https://platform.openai.com/docs/introduction

In [ ]:
! pip install openai

In [ ]:
TOKEN = 'sk-C'

### GPT Completion

In [ ]:
import openai

openai.api_key = TOKEN
res = openai.Completion.create(
  model="text-davinci-003",
  prompt="請介紹什麼是ChatGPT",
  max_tokens = 1000
)

print(res.choices[0].text)



ChatGPT (Chat Generative Pre-trained Transformer) 是一種基於文字生成的預訓練轉換器架構，可以用於應用於自然語言生成的任務。它是在 GPT2 上修訂而成，並在聊天機器人中使用，可以生成上下文相關的休閒及對話。ChatGPT 可用於 Facebook Messenger、Slack 和 WeChat 應用程序中，利用該技術能夠增加有意義并符合語境的答案。它可以根據自然語言來自動生成聊天機器人的話語，對於用戶的問題做出真實的回答，改善客戶服務經驗。


In [ ]:
script = """
User: 請幫我新上架的人工智慧語音轉文字雲服務，寫個100字介紹文
AI: 人工智慧語音轉文字雲服務，專為企業客戶而生。服務利用即時技術將每一個語音檔案轉換成文字，可支援多種語言，能夠提供不受限的內容轉換，讓你的工作效率最大化。此外，我們的服務不受網路速度限制，功能強大而易於使用，可根據個性需求定制解決方案。我們的服務具有高精度的語音轉換能力，可支援多種非常多的口音和語境，實現無縫接軌的文字服務和轉換。總之，沒有比人工智慧語音轉文字雲服務更好的方式來轉換文字了。
User: 請根據介紹文幫我產生一個朗朗上口的標題
"""
res = openai.Completion.create(
 model="text-davinci-003",
 prompt=script,
 max_tokens = 1000
)

print(res.choices[0].text)



AI: 人工智慧語音轉文字：無縫接軌的高精度轉文服務！


### GPT Chat

In [ ]:
product = "人工智慧語音轉文字雲服務"

completion = openai.ChatCompletion.create(
 model="gpt-3.5-turbo",
 messages=[
  {"role": "user", "content": f"請幫我新上架的{product}, 寫個100字介紹文"},
  {"role": "assistant", "content": "我們的新上架人工智慧語音轉文字雲服務，是一種高效、方便的文字轉換工具，可以將人類發出的語音轉換為文字。使用者只需錄製自己的語音，上傳至平台，即可快速獲得轉換後的文字內容。本服務採用了最先進的語音辨識技術，能夠準確辨識各種不同語言和口音，支援多種檔案格式。無論是研究工作還是商務會議，都能夠有效提高工作效率，節省大量時間。歡迎大家體驗這一嶄新且實用的服務！"},
  {"role": "user", "content": "請根據介紹文幫我產生一個朗朗上口的標題"}]
)
print(completion.choices[0].message.content)

「即錄即換，高效語音轉文字服務讓工作無負擔！」


## LangChain

In [ ]:
! pip install langchain

### LangChain Chat 範例

In [ ]:
from langchain.chat_models import ChatOpenAI

from langchain.prompts.chat import (
  ChatPromptTemplate,
  SystemMessagePromptTemplate,
  HumanMessagePromptTemplate,
)

chat = ChatOpenAI(temperature=0, openai_api_key = TOKEN)

template=" 請幫我新上架的{product}，寫個100字介紹文"
system_message_prompt = SystemMessagePromptTemplate.from_template(template)
human_template="請根據介紹文幫我產生一個朗朗上口的標題"
human_message_prompt = HumanMessagePromptTemplate.from_template(human_template)
chat_prompt = ChatPromptTemplate.from_messages([system_message_prompt, human_message_prompt])

ret = chat(chat_prompt.format_prompt(product="人工智慧語音轉文字雲服務").to_messages())

ret.content

### Document Loading

In [ ]:
! gdown https://drive.google.com/uc?id=1Z_ww5ZASdIq0uZrg8jt_d7E_PzFQdYH-

Downloading...
From: https://drive.google.com/uc?id=1Z_ww5ZASdIq0uZrg8jt_d7E_PzFQdYH-
To: /content/TSMC2023Q1.zip
100% 10.7M/10.7M [00:00<00:00, 108MB/s]


In [ ]:
! unzip TSMC2023Q1.zip

Archive:  TSMC2023Q1.zip
replace TSMC2023Q1/20230330 TSMC Citi.pdf? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [ ]:
from langchain.document_loaders import PyPDFLoader
loader = PyPDFLoader('TSMC2023Q1/20230330 TSMC Citi.pdf')

In [ ]:
pages = loader.load()
len(pages)

15

In [ ]:
pages[0].page_content

'See Appendix A-1 for Analyst Certification, Important Disclosures and Research Analyst Affiliations.\nCiti Research is a division of Citigroup Global Markets Inc. (the "Firm"), which does and seeks to do business with companies covered in its research \nreports. As a result, investors should be aware that the Firm may have a conflict of interest that could affect the objectivity of this report. Investors should \nconsider this report as only a single factor in making their investment decision. Certain products (not inconsistent with the author\'s published research) are \navailable only on Citi\'s portals.30 Mar 2023 07:47:50 ET │ 15 pages   \n \nTSMC (2330.TW)\nAssessing the Potential Upside from AI \nCITI\'S TAKE \nAI is witnessing a potential “iPhone moment” and should be a L-T catalyst in \nthe semi industry, despite still small contribution at current early stage. nVidia \ndominates the data center GPU market for now, while we expect to see more \nAI chips in future designed by h

### Splitting

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from langchain.text_splitter import NLTKTextSplitter
splitter = NLTKTextSplitter(chunk_size = 1000, chunk_overlap = 200 )
chunks = splitter.split_text(pages[0].page_content)

In [ ]:
chunks[0]

'See Appendix A-1 for Analyst Certification, Important Disclosures and Research Analyst Affiliations.\n\nCiti Research is a division of Citigroup Global Markets Inc. (the "Firm"), which does and seeks to do business with companies covered in its research \nreports.\n\nAs a result, investors should be aware that the Firm may have a conflict of interest that could affect the objectivity of this report.\n\nInvestors should \nconsider this report as only a single factor in making their investment decision.\n\nCertain products (not inconsistent with the author\'s published research) are \navailable only on Citi\'s portals.30 Mar 2023 07:47:50 ET │ 15 pages   \n \nTSMC (2330.TW)\nAssessing the Potential Upside from AI \nCITI\'S TAKE \nAI is witnessing a potential “iPhone moment” and should be a L-T catalyst in \nthe semi industry, despite still small contribution at current early stage.'

### Embedding

In [ ]:
import numpy as np

res = openai.Embedding.create(
 model="text-embedding-ada-002",
 input="我們新上架的人工智慧語音轉文字雲服務，是一種高效、方便的文字轉換工具，可以將人類發出的語音轉換為文字。"
)

np.array(res.data[0].embedding)

array([-0.02235476, -0.01564317,  0.00637924, ..., -0.00109063,
       -0.00663415, -0.01057075])

In [ ]:
def get_embedding(input_sentence):
 res = openai.Embedding.create(
  model="text-embedding-ada-002",
  input= input_sentence
 )
 return np.array(res.data[0].embedding)


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
vec_list = []
for sentence in ['樹上的蘋果又大又紅，看起來很好吃',
                 'iphone14 是您聖誕節不可以錯過的最佳禮物選擇',
                 '蘋果公司執行長對iphone新機發表聲明']:
 vec = get_embedding(sentence)
 vec_list.append(vec)

m = np.vstack(vec_list)
cosine_similarity(m)


array([[1.        , 0.79647616, 0.80737102],
       [0.79647616, 1.        , 0.82777462],
       [0.80737102, 0.82777462, 1.        ]])

In [ ]:
from langchain.embeddings.openai import OpenAIEmbeddings
embedding = OpenAIEmbeddings()

embedding1 = embedding.embed_query('樹上的蘋果又大又紅，看起來很好吃')
embedding2 = embedding.embed_query('iphone14 是您聖誕節不可以錯過的最佳禮物選擇')
embedding3 = embedding.embed_query('蘋果公司執行長對iphone新機發表聲明')

In [ ]:
m = np.vstack([embedding1, embedding2, embedding3])
cosine_similarity(m)

array([[1.        , 0.79649865, 0.80748742],
       [0.79649865, 1.        , 0.82783715],
       [0.80748742, 0.82783715, 1.        ]])

### VectorStore (Chroma)

In [ ]:
! pip install chromadb

In [ ]:
! pip install tiktoken

In [ ]:
from langchain.vectorstores import Chroma
persist_directory = 'docs/chroma/'
vectordb = Chroma.from_texts(
    texts=chunks,
    embedding = embedding,
    persist_directory=persist_directory
)

In [ ]:
len(chunks)

5

In [ ]:
print(vectordb._collection.count())

5


### Query

In [ ]:
question = '#zh-tw 請問citi 對台積電的看法? 請用正體中文'
docs = vectordb.similarity_search(question,k=3)
docs

### Quesion & Answer

In [ ]:
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(model_name="gpt-3.5-turbo-0613", temperature=0)

qa_chain = RetrievalQA.from_chain_type(
    llm,
    retriever=vectordb.as_retriever()
)

result = qa_chain({"query": '#zh-tw 請問citi 對台積電的看法? 請用正體中文'})

In [ ]:
result['result']

'Citi對台積電的看法是積極的。他們預計台積電在2024年將有更好的前景，這要歸功於其在人工智能和高性能計算方面的堅實項目。Citi建議繼續買入台積電股票，目標價格維持在NT$620。他們預計台積電的股價回報率為15.9%，股息收益率為2.2%，預計總回報率為18.1%。此外，根據Citi的研究，台積電在2023年和2024年的盈利預測也是積極的。'

##LangChain 應用開發總流程

### 將所有PDF 鍵入索引資料庫

In [ ]:
from langchain.document_loaders import PyPDFLoader
import glob

# Load PDF
loaders = []
for f in glob.glob('TSMC2023Q1/*'):
  pdf_doc = PyPDFLoader(f)
  loaders.append(pdf_doc)

docs = []
for loader in loaders:
    docs.extend(loader.load())

### 分割文檔(Splitting)

In [ ]:
from langchain.text_splitter import RecursiveCharacterTextSplitter
splitter = NLTKTextSplitter(chunk_size = 1000, chunk_overlap = 200 )
splits = splitter.split_documents(docs)

### 建立索引資料庫

In [ ]:
vectordb = Chroma.from_documents(
    documents=splits,
    embedding=embedding,
    persist_directory='docs/chroma2/'
)

###  對資料庫進行問答

In [ ]:
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(model_name="gpt-3.5-turbo-0613", temperature=0)

qa_chain = RetrievalQA.from_chain_type(
    llm,
    retriever=vectordb.as_retriever()
)

result = qa_chain({"query": '#zh-tw 請問JPM對台積電目標價的看法? 請用正體中文回答'})

In [ ]:
result["result"]

'根據提供的資訊，J.P. Morgan對台積電的目標價為NT$650.0。'

## EmebedChain

In [ ]:
! pip install embedchain

In [ ]:
import os
os.environ["OPENAI_API_KEY"] = TOKEN

In [ ]:
from embedchain import App

chat_bot = App()

In [ ]:
chat_bot.chat("請幫我新上架的人工智慧語音轉文字雲服務，寫個100字介紹文")

'我們最新上架的人工智慧語音轉文字雲服務是一個強大的工具，可以將語音檔案轉換為文字，並生成文字雲。這個服務使用先進的語音辨識技術，能夠準確地將語音轉換為文字，並且支援多種語言。生成的文字雲可以幫助用戶更好地理解和分析語音內容，並提取關鍵詞和主題。此外，我們的服務還提供了一個直觀易用的界面，讓用戶可以輕鬆上手並快速完成轉換和生成文字雲的操作。無論是在學術研究、商業分析還是其他領域，我們的人工智慧語音轉文字雲服務都能為您提供有價值的信息和洞察力。'

In [ ]:
chat_bot.chat("請根據介紹文幫我產生一個朗朗上口的標題")

'「深度解析語音內容，輕鬆生成文字雲」'

### 利用 EmbedChain 建立ChatPDF

In [ ]:
from embedchain import App
bot = App()
for f in glob.glob('TSMC2023Q1/*'):
  bot.add('pdf_file', f)

Successfully saved TSMC2023Q1/20230410 TSMC JPM.pdf. Total chunks count: 45
Successfully saved TSMC2023Q1/20230411 TSMC GS.pdf. Total chunks count: 102
Successfully saved TSMC2023Q1/20230410 TSMC DW.pdf. Total chunks count: 134
Successfully saved TSMC2023Q1/20230414 TSMC NMR.pdf. Total chunks count: 188
Successfully saved TSMC2023Q1/20230330 TSMC Citi.pdf. Total chunks count: 275
Successfully saved TSMC2023Q1/20230331 TSMC UBS.pdf. Total chunks count: 418
Successfully saved TSMC2023Q1/20230417 TSMC HSBC.pdf. Total chunks count: 467
Successfully saved TSMC2023Q1/20230406 TSMC MS.pdf. Total chunks count: 546
Successfully saved TSMC2023Q1/20230412 TSMC CL.pdf. Total chunks count: 606
Successfully saved TSMC2023Q1/20230410 TSMC HTI.pdf. Total chunks count: 653


In [ ]:
bot.query('#zh-tw 請問JPM對台積電目標價的看法? 請用正體中文回答')

'根據報告，J.P. Morgan對台積電的目標價為NT$650.0。'

In [ ]:
bot.count()

653

In [ ]:
bot.reset()

In [ ]:
bot.count()

0